//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosRol
    {
        public int Id { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdPermiso { get; set; }
    
        public virtual Permisos Permisos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
